### PR TITLE
Address indentation levels and better handing of hanging indents

### PR DESCRIPTION
**Pull request by alanmcruickshank**
Addresses the concerns around indentation fix rules from #180 .

Doesn't yet include a linting rule for the `WITH` clause. If that sounds like a sensible idea, I'll add that to this PR before merging.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
Now includes a linting rule for the indentation of the closing bracket on a `WITH` clause.

**Comment by moseleyi** [comment]
@alanmcruickshank can you tell me why the L033 rule is triggered for the following code:

```sql

23 | time_series AS (
24 |     SELECT
25 |         table.*
26 |     FROM table
27 | ),
```

```L:  24 | P:   5 | L003 | Expected 0 indentations, found 2 [compared to line 23]```

**Comment by tunetheweb** [comment]
That indeed seems like a bad error message. The actual error message should be:

```
L: 24 | P: 5 | L003 | Expected 1 indentations, found 2 [compared to line 23]
```

And if you correct the SQL to have only two spaces (instead of 4), then it no longer complains (i.e. it allows 1 indentation despite saying it wants 0). And running `fix` also uses 1 indentation.

As this issue is closed, could you open a new one to investigate and correct this error message?

**Comment by moseleyi** [comment]
Sure: https://github.com/sqlfluff/sqlfluff/issues/3588

**Pull request merged**
