### PR TITLE
[WIP] #105: Transaction, DDL, and permission statements

### PR DESCRIPTION
**Pull request by barrywhart**
Addresses #102. Several of these are not fully supported, but at least cover the more common cases.

- [X] `COMMIT` and `ROLLBACK` statements
- [x] `DROP TABLE` and `DROP VIEW` statements
- [x] `GRANT` statement
- [x] `REVOKE` statement
- [x] `CREATE` statement. See question for this one: Unsolved parsing issue for column constraints

### CODE REVIEW

**Comment by barrywhart** [comment]
@alanmcruickshank: The "DeepSource: Python" check is failing with a couple of errors like:
`Method 'from_raw' is abstract in class 'BaseSegment' but is not overridden`

Do I need to fix this? I think I'm following the same pattern used by other parts of the grammar.

**Comment by barrywhart** [comment]
@alanmcruickshank: I think this PR is ready for review. It doesn't cover every possible option for these statements, but I think it covers the ~80% case, perhaps? Maybe we should ask the person who created the related issue to see if it meets their needs.

There is one significant issue I need help with -- getting column constraints to parse correctly. See the `HOW DO I DO THIS?` comment on `ColumnDefinitionSegment`. 

Also, on some of my commits,  the "DeepSource: Python" check complains about: `Method 'from_raw' is abstract in class 'BaseSegment' but is not overridden`. Other times it doesn't. Is this a real issue with the code? Why is the behavior seemingly inconsistent?

**Comment by alanmcruickshank** [comment]
@barrywhart  - don't worry about the deepsource fail for now. It's quite diligent, but a little brutal at times. I've only just enabled it and I haven't tuned the settings yet 😃 .

I really like how you've gone about this, I haven't reviewed in full yet, but I did take a look at the section where you asked about column constraints. Excellent question. My best suggestion would be to use the `AnyNumberOf` grammar, which is used in the similar use case of the `JoinClauseSegment`. Join statements are often chained without any real delimiter. The arguments to the `AnyNumberOf` grammar would be a selection of the possible elements which could follow it.

See if that works, and then I'll give this PR a proper review. Thanks so much for taking the time to work on this - I think it's looking really good!

**Comment by barrywhart** [comment]
@alanmcruickshank: Thanks -- your suggestion to use `AnyNumberOf` worked. I think this is ready for review now.

**Comment by alanmcruickshank** [comment]
Looks great to me @barrywhart - thanks for this. I'll add the relevant bits to the changelog, merge in my other work too and then I might publish an alpha release of 0.3.0 for testing.

**Comment by barrywhart** [comment]
That's great news! It would be good to have a new release soon -- there have been many fixes and improvements since December.

**Pull request merged**
