### PR TITLE
Change to attempt fix for installation problem on MacOS

### PR DESCRIPTION
**Pull request by alanmcruickshank**
@ryantuck I think this should fix your issue (#211).

Can you try installing from this git branch and see whether it works? If so I'll merge these changes.

### CODE REVIEW

**Comment by ryantuck** [comment]
Hey @alanmcruickshank thanks for looking into this. I unfortunately got the same error using `pip install .` locally on this branch.

If you have other suggestions for what I should try, I'm definitely down to experiment more!

```
• ~/src/sqlfluff $ pip list | grep sqlfluff
• ~/src/sqlfluff $ git status
On branch ac/clearup
Your branch is up to date with 'origin/ac/clearup'.

nothing to commit, working tree clean
• ~/src/sqlfluff $ pip install .
Processing /Users/ryan.tuck/src/sqlfluff
Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.7/site-packages (from sqlfluff==0.3.1) (7.0)
Requirement already satisfied: colorama>=0.3 in /usr/local/lib/python3.7/site-packages (from sqlfluff==0.3.1) (0.3.9)
Requirement already satisfied: oyaml in /usr/local/lib/python3.7/site-packages (from sqlfluff==0.3.1) (0.9)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.7/site-packages (from sqlfluff==0.3.1) (2.10.1)
Requirement already satisfied: diff-cover<3.0,>=2.5.0 in /usr/local/lib/python3.7/site-packages (from sqlfluff==0.3.1) (2.6.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from oyaml->sqlfluff==0.3.1) (5.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2->sqlfluff==0.3.1) (1.1.1)
Requirement already satisfied: jinja2-pluralize in /usr/local/lib/python3.7/site-packages (from diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (0.3.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/site-packages (from diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (2.2.0)
Requirement already satisfied: pluggy in /usr/local/lib/python3.7/site-packages (from diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (0.13.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.7/site-packages (from diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (1.12.0)
Requirement already satisfied: inflect>=0.2.4 in /usr/local/lib/python3.7/site-packages (from jinja2-pluralize->diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (4.1.0)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from pluggy->diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (1.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pluggy->diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (0.6.0)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata>=0.12; python_version < "3.8"->pluggy->diff-cover<3.0,>=2.5.0->sqlfluff==0.3.1) (4.3.0)
Building wheels for collected packages: sqlfluff
  Building wheel for sqlfluff (setup.py) ... done
  Created wheel for sqlfluff: filename=sqlfluff-0.3.1-cp37-none-any.whl size=109652 sha256=2d930f07d2b5c8354ba0a40706972668758cfc104044a86275af1f5c4238c117
  Stored in directory: /private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-ephem-wheel-cache-tz8pur0x/wheels/04/4c/64/cf283d0579f21c870ea83e03401daef522bbaed6394c1d2ef8
Successfully built sqlfluff
Installing collected packages: sqlfluff
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/CHANGELOG.md'
Consider using the `--user` option or check the permissions.

• ~/src/sqlfluff $
```

**Comment by alanmcruickshank** [comment]
Hmmmm, I'm not sure what to try next, but if you're happy to do some debugging, I've just pushed another commit. It will *intentionally* fail, but will also spit out an error which should help with the debugging.

This might take a few tries, but if you're happy to try a few then hopefully we can get to the bottom of this.

For transparency, you'll see that the most recent commit adds an intentional error raise when the setup.py script tries to read anything and spits out the current filepath and also the content of both the default path and of what *i think* is the path to the running file.

**Comment by ryantuck** [comment]
Yeah, let's get this figured out!

Latest error output:

```
• ~/src/sqlfluff $ git log | head
commit 44eb7bb6a3fc05058461ef14c18e47e4d7f5a4cd
Author: Alan Cruickshank <alanmcruickshank@gmail.com>
Date:   Mon Apr 6 19:28:51 2020 +0100

    Intentional raise for debugging

...

• ~/src/sqlfluff $ pip install .
Processing /Users/ryan.tuck/src/sqlfluff
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/setup.py'"'"'; __file__='"'"'/private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/pip-egg-info
         cwd: /private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/setup.py", line 59, in <module>
        long_description=read('README.md') + "\n\n---\n\n" + read('CHANGELOG.md'),
      File "/private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t/setup.py", line 46, in read
        here_content=here_content))
    ValueError: Intentional error for debugging. here: '/private/var/folders/q2/fqwqkct16jd986v6z95np2qw0000gp/T/pip-req-build-qgkerh8t', def_content: ['LICENSE.md', 'requirements.txt', 'test', 'CHANGELOG.md', 'util.py', 'MANIFEST.in', 'docs', '.readthedocs.yml', '.deepsource.toml', 'README.md', 'setup.py', '.gitignore', 'CONTRIBUTING.md', 'benchmarks', 'tox.ini', 'pip-egg-info', '.git', 'pip-delete-this-directory.txt', '.circleci', 'src'], here_content: ['LICENSE.md', 'requirements.txt', 'test', 'CHANGELOG.md', 'util.py', 'MANIFEST.in', 'docs', '.readthedocs.yml', '.deepsource.toml', 'README.md', 'setup.py', '.gitignore', 'CONTRIBUTING.md', 'benchmarks', 'tox.ini', 'pip-egg-info', '.git', 'pip-delete-this-directory.txt', '.circleci', 'src'].
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by alanmcruickshank** [comment]
@ryantuck - ok. so the file *is* there, it's just not allowing us to access it. Taking a different approach this time. I don't think it matters if we can't access the file at this point - it's mostly useful for populating pypi. Given that I've defaulted to just returning the filename if we don't have permission to access the file. See if that fixes things or whether we get a different error?

**Comment by ryantuck** [comment]
@alanmcruickshank I messed around with this locally and think I figured out a solution, and provided it in #223. The issue didn't appear related to _reading_ anything, but rather attempting to write to `/usr/local`, which was forbidden. 

Thanks for going back-and-forth with me on this!

**Pull request closed without merging**
