### PR TITLE
Array notation and match caching

### LINKED ISSUE #59: Enhancement: Support for BigQuery SQL
Our data science projects use Google BigQuery. It will be good if this is supported. It's pretty close to standard SQL, I think.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
Implements Array notation as per #59. Also introduces some very lightweight pruning of match paths which have already been tried using the `ParseBlacklist` class.

@barrywhart This implements parsing for array notation - can you take a look at the example queries that it parses and see if they're what you had in mind?

Fixed #59

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
@barrywhart This implements parsing for array notation - can you take a look at the example queries that it parses and see if they're what you had in mind?

**Comment by alanmcruickshank** [comment]
Now also:
Fixes #178 
Fixes #179

**Comment by barrywhart** [comment]
I tested this on the original query.
* I no longer see parse errors related to array notation. 💯 
* I found what may be a new issue with `CAST` syntax. See below.
* I'm still seeing the other problem noted in the same issue, where BigQuery table references don't parse correctly (due to the backquotes, I think). Is this still expected?
* Parsing performance may be starting to become a concern. On Python 3.6, one of our queries (about 250 lines long) takes almost *19 seconds* to parse. It may be interesting to try running SQLFluff with PyPy to see how that performs.

This is the test query I used:
```
WITH age_buckets_bit_array AS (
    SELECT
      bucket_id,
      num_ranges,
      min_age,
      ARRAY(SELECT CAST(num AS INT64) FROM UNNEST(SPLIT(binary, '')) AS num) AS bits,
      age_label
    FROM
      age_buckets
  ),
  bucket_abundance AS (
    SELECT
      bucket_id
      (count_18_24 * bits[OFFSET(0)] + count_25_34 * bits[OFFSET(1)] +
       count_35_44 * bits[OFFSET(2)] + count_45_54 * bits[OFFSET(3)] +
       count_55_64 * bits[OFFSET(4)] + count_65_plus * bits[OFFSET(5)]) / audience_size AS relative_abundance
    FROM
      audience_counts_gender_age
    CROSS JOIN
      age_buckets_bit_array
  )

SELECT
  *
FROM
  age_buckets_bit_array
JOIN
  bucket_abundance
USING (bucket_id)
```

Results (note the parse error on line 6):
```
$ time sqlfluff lint sql/predicted_demographics_processing/user_age_labels[user_id,list_id].sql
== [sql/predicted_demographics_processing/user_age_labels[user_id,list_id].sql] FAIL
L:   3 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   4 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   5 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   6 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   6 | P:  13 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:   6 | P:  20 |  PRS | Found unparsable segment @L006P020: 'CAST(num AS INT64) F...'
L:   6 | P:  86 | L016 | Line is too long.
L:   7 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   9 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  10 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  11 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  13 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  13 | P:  16 | L017 | Function name not immediately followed by bracket.
L:  14 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  14 | P:  70 | L007 | Operators near newlines should be after, not before the newline.
L:  15 | P:  70 | L007 | Operators near newlines should be after, not before the newline.
L:  16 | P:   8 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  16 | P:  73 | L006 | Operators should be preceded by a space.
L:  16 | P: 110 | L016 | Line is too long.
L:  18 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  20 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  21 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  24 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  26 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  28 | P:   3 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  29 | P:   1 | L003 | Indent expected and not found compared to line #27
```

**Comment by barrywhart** [comment]
Thanks for your hard work, @alanmcruickshank!! I'm really excited about this work. I've been talking about it at work to anyone who will listen. 🙂

**Comment by alanmcruickshank** [comment]
Thanks @barrywhart .

I'm going to merge this PR in that case.

- For the back-quotes, have you tried using `--dialect bigquery` at the command line? I think that should solve that problem
- I'm going to look into the `CAST(num AS INT64)` issue now. I thought hat had been solved but evidently not.
- As for performance, yeah, I've noticed a it already. I think that might be a bigger stream of work going forward, although I've really not done much performance optimisation AT ALL at the moment so there should be some pretty low hanging fruit.

**Comment by barrywhart** [comment]
About the backquotes, I thought I had set "dialect = bigquery" in .sqlfluff. I'll double check that and try the command-line option as well.

**Comment by alanmcruickshank** [comment]
@barrywhart if you add `-v` to the command then you'll get a readout of the configuration and it will say which dialect it's running in.

**Comment by barrywhart** [comment]
It looks like the `dialect` setting in `.sqlfluff` is not working, but `--dialect bigquery` works. I'll create a new issue for this.

**Pull request merged**
