### PR TITLE
Issue 85: Integrate with diff_cover's quality checking tool

### PR DESCRIPTION
**Pull request by barrywhart**
This PR addresses #85. It will not work until the [PR in that repo](https://github.com/Bachmann1234/diff_cover/pull/128) is merged and a new release is available with those changes.

- [x] Implement the integration
- [x] Update the required `diff_cover` in `setup.py` version once there's an updated `diff_cover` release with these changes
- [x] Add tests

### CODE REVIEW

**Comment by barrywhart** [comment]
Example output:
```
$ diff-quality --violations sqlfluff
-------------
Diff Quality
Quality Report: sqlfluff
Diff: origin/master...HEAD, staged and unstaged changes
-------------
sql/audience_size_queries/constraints/_postcondition_check_gdpr_compliance.sql (0.0%):
sql/audience_size_queries/constraints/_postcondition_check_gdpr_compliance.sql:5: Inconsistent capitalisation of unquoted identifiers.
-------------
Total:   1 line
Violations: 1 line
% Quality: 0%
-------------
```

**Comment by alanmcruickshank** [comment]
@barrywhart - wow this looks really interesting! I'm not going to review it yet, so that I can wait for your PR on that project to get accepted and then I can test properly, but in principle this could be pretty awesome. Thanks for submitting!

**Comment by barrywhart** [comment]
I think the build failure is not related to my changes. It's failing in Python 3.4 because the `colorama` package does not support Python 3.4. @alanmcruickshank, can you confirm if `colorama` is a known dependency of any of the existing SQLFluff dependencies?

**Comment by barrywhart** [comment]
If you want to take an initial look, feel free. You can also try out the changes by cloning my [fork of the repo](https://github.com/barrywhart/diff_cover) and running `pip install -e .` against the [`bhart-issue_8_quality_plugins`](https://github.com/barrywhart/diff_cover/tree/bhart-issue_8_quality_plugins) branch.

**Comment by alanmcruickshank** [comment]
@barrywhart - we use `colorama` for coloured output on the console via click. Usage of the sqlfluffis pretty low on py3.4 and the only degredation of function would be coloured command line output.

I'm happy to make the `colorama` library *not* a requirement for python 3.4. I think the best way of doing that would be to add an environment marker to the `requirements.txt` for that library.

Instead of:
```
colorama>=0.3
```

We should have:
```
# Colorama is not available in py34, and so coloured output is not enabled
colorama>=0.3; python_version!='3.4'
```

I've never used environment markers before, but they seem to be designed for this purpose: https://www.python.org/dev/peps/pep-0345/#environment-markers

**Comment by barrywhart** [comment]
Yes, environment markers seem like a natural approach. A second set of changes will also be necessary: When you `import` the library in Python 3.4 code, it will fail. You'll need to catch the exception, something like

```
try:
    import <something>
except ImportError:
    pass
```

I'll take a closer look at the Python 3.4 build errors and provide additional detail. If you want, I can probably take care of this, either in this PR or a separate one.

**Comment by barrywhart** [comment]
I updated the required `diff-cover` version to the pending 2.5.0 release, which will add the plugin feature. The builds will all fail until this is released. I still need to address the `colorama` dependency in Python 3.4 as well.

**Comment by barrywhart** [comment]
I have a question about `requirements.txt`. That file contains `colorama`, but `setup.py` does not. If I understand correctly, a user installing SQLFluff will get the list of packages in `setup.py`, and `requirements.txt` is not involved. Are the two files related to one another somehow?

**Comment by barrywhart** [comment]
Update on the related `diff_cover` changes:
* My PR has been merged
* The author noticed a small problem caused by my PR, and has created another PR to address those and bump the package version number to 2.5.0.
* I think that follow-up PR will be merged in the next few days and version 2.5.0 will be released.
* Once that happens, I think the builds for this PR will all pass (they will probably have to be manually triggered, e.g. with a dummy git commit).

**Comment by barrywhart** [comment]
Automated tests are passing now except for the coverage check (including Python 3.4). I'll add tests early this week (Monday or Tuesday).

**Comment by barrywhart** [comment]
Tests passing everywhere, including Python 3.4. 100% test coverage for the new code. This is ready for review.

**Comment by barrywhart** [comment]
@alanmcruickshank: I believe this is ready for review, when you have an opportunity. Thanks!

**Comment by alanmcruickshank** [comment]
Thanks @barrywhart - one thing I'd love to do is add this functionality to the documentation. I've merged these changes regardless, and I'll make an issue for that.

**Pull request merged**
